### PR TITLE
use InternationalCitiesStaticList, add G778

### PR DESCRIPTION
**Pull request by michelepizzi**

### CODE REVIEW

**Comment by robertogallea** [comment]
Hi Michele and thank you for your contribution
Could you please fix the styleCI issue and add the missing city also to the ItalianCitiesStaticList ?

Thanks!

**Comment by michelepizzi** [comment]
Hi, I fix CodiceFiscale.php and added G778 to the Italian Cities List

**Comment by robertogallea** [comment]
Thanks!

**Comment by robertogallea** [comment]
Released in v1.4.2

**Pull request merged**
