### PR TITLE
Undefined array key "G"

### PR DESCRIPTION
**Pull request by caiojhonny**
Prevent warning:
Undefined array key "G" in vendor/robertogallea/laravel-codicefiscale/src/CodiceFiscale.php on line 179.

Codice Fiscale Value used for tests: GNIWCF85G08P870X

## Description

Preventing warning "Undefined array key" using value: GNIWCF85G08P870X 

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by robertogallea — CHANGES_REQUESTED** [review]
Why are you assigning the result of `array_key_exists()` to `month` field?

**Comment by caiojhonny** [comment]
> Why are you assigning the result of `array_key_exists()` to `month` field?

Because there is no verification of the key into tabDecodeMonths and a warning is generated:
Undefined array key "G" in vendor/robertogallea/laravel-codicefiscale/src/CodiceFiscale.php on line 179.

Can you try to reproduce the same error using this codice fiscale: GNIWCF85G08P870X?

Thanks

**Comment by caiojhonny** [comment]
You right, sorry for that.

I corrected my file.

The logic is:
If the key exists on array "$this->tabDecodeMonths", proceed, if not is null.

This prevents the warning.

Thanks

**Comment by robertogallea** [comment]
Sure, I got that, but was wondering if I was missing something in your syntax. 😉

Thanks!

**Review by robertogallea — COMMENTED** [review]
Would you mind extracting a variable for the repetition in substr(...)?

Thanks!

**Comment by caiojhonny** [comment]
> Would you mind extracting a variable for the repetition in substr(...)?
> 
> Thanks!

Done. Thanks!

**Comment by robertogallea** [comment]
That's it! Thank you!

**Pull request merged**
